### PR TITLE
Events

### PR DESCRIPTION
**Pull request by krisbobo**
## Milestone: Handle events
*The following changes are being introduced:*
- Imported files to the Calculator component.
- Implemented event handlers to ensure the logic works with our component.
- Tested on the browser to ensure it renders properly.

### CODE REVIEW

**Review by BertrandConxy — CHANGES_REQUESTED** [review]
Hi @krisbobo, 

Good job so far! 👏 👏 
There are some issues that you still need to work on to go to the next project but you are almost there! 🏃‍♂️ 🏃‍♂️ 


## Highlights 💪 
- No linter errors
- correct flow is used
- good PR

## Required Changes ♻️

- [x] Good job so far 👏 👏 I have seen an issue while testing your calculator. The division operator `/`  is making app crashes for a reason I have not figured out yet. I have recorded a video in order to show you what I mean and here is the [link](https://www.loom.com/share/9c31e2b969a6436a892065d4bc0b7118)
Please try to fix 😃 👍 Apart from that everything is good 👏 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @BertrandConxy in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by krisbobo** [comment]
Hi @BertrandConxy 
Thanks for attaching a video description. 
I have been able to figure out the issue. I used the standard `/` for division whereas `÷` was supposed to be used, from the calculator logic. Thanks for pointing this out.

**Comment by BertrandConxy** [comment]
@krisbobo You are welcome 😊

**Review by omarsalem7 — APPROVED** [review]
Hi @krisbobo 😊, 
# STATUS: APPROVED! 🥇 💯 

giphy

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Descriptive pull request 
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 
✅ Division works properly now
Recording 2022-12-10 at 17 44 22


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
